### ISSUE TITLE
Validattion code for Overall Performance?

### ISSUE THREAD

**Issue by xmu-xiaoma666** [yanmin-wu/EDA#3]
Thanks for your great job.
I notice that only Unique and Multiple performances are provided in your code. Can you share validation code for Overall Performance?

**Comment by yanmin-wu** [comment]
Thanks for your interest. 
You can double-check it. In fact, the overall performance is already provided. Our final performance is determined using the semantic alignment results from the last layer of the Decoder. As shown below.


![Screenshot from 2023-03-12 21-19-29](https://user-images.githubusercontent.com/52712492/224547482-e43a81ba-cbf7-42b2-ae30-d8baece2a866.png)

**Comment by xmu-xiaoma666** [comment]
Thanks for your great response. I find the performance for each head is 0. Do you konw why this happens?
![image](https://user-images.githubusercontent.com/33897496/224594746-c4202706-c45e-49d5-b56a-8213f64130ed.png)

**Comment by yanmin-wu** [comment]
I apologize for forgetting to comment out these two lines. [L174](https://github.com/yanmin-wu/EDA/blob/master/train_dist_mod.py#L174) - [L175](https://github.com/yanmin-wu/EDA/blob/master/train_dist_mod.py#L175)
```python
# note only consider the last layer
if prefix != 'last_':
   continue
```
I only kept the evaluation output of the last layer. Actually, you only need to refer to the results from this layer.
