### ISSUE TITLE
Question of visualization

### ISSUE THREAD

**Issue by qzp2018** [yanmin-wu/EDA#4]
Thanks for your excellent job.I have run through your code,but because  I just entered this research field recently,so I have problem to visualize your results,such as detection frame like Figure 1.Would you please 
release code of visualization?Thank you very much!

**Comment by yanmin-wu** [comment]
Thanks for your interest. We will release the visualization script soon.

**Comment by xinpuliu** [comment]
Hi, 
Do you already know how to visualize? I need your help！
Thanks！
