### ISSUE TITLE
I am confused about the log.txt file

### ISSUE THREAD

**Issue by linhaojia13** [yanmin-wu/EDA#6]
1. I downloaded your publicly available log file `log_67_6.txt`  regarding Sr3D, and noticed something strange: the `max_epoch` parameter recorded in the log file is 300, but according to the log file, the training lasted for only 48 epochs. Can you explain why? Did you manually stop the program?

2. When I ran the command `sh scripts/train_sr3d.sh`, the log.txt showed that the `max_epoch` was 400, and the training seemed to really continue towards 400 epochs. Therefore, I had to manually stop the program at the 75th epoch.

3. In your published log file, log_67_6.txt, detailed validation rerults is output every 3 epochs, but this does not happen when I run `sh scripts/train_sr3d.sh`. I have included a [link](https://drive.google.com/file/d/1GH7TEHWAgcvh6VR1dCsIK6TdlwOnV9xG/view?usp=share_link) to my log file for your reference at any time.

**Comment by yanmin-wu** [comment]
Thanks for your interest.
+ **1/2**. 'max_epoch' is just a setting for the upper limit of training, and in practice, training can be terminated early based on performance.
+ **3**. Have you observed the terminal output, is it the same as the log file?

**Comment by linhaojia13** [comment]
Thank you! I have resolved all these issues.
