### ISSUE TITLE
The pretrained PointNet++ backbone

### ISSUE THREAD

**Issue by linhaojia13** [yanmin-wu/EDA#8]
Hi, is file "gf_detector_l6o256.pth" the backbone weights of the Group-Free which is trained on ScanNet with a vocabulary of 485 object categories ?

**Comment by yanmin-wu** [comment]
Yes. But according to our experiments, training our network from scratch without using the pre-trained pointnet++ weight can also achieve comparable performance.

**Comment by linhaojia13** [comment]
Thank you very much!
